#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../../autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require_once $file;
        define('DIR_VENDOR', realpath(dirname($file)));
        break;
    }
}

\Copona\Helpers\Util::load_cp();

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Copona\Cli\Commands\CacheClearCommand());
$application->run();