version: '2.0'
services:
  db:
    env_file:
      - .env
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: copona
    volumes:
      - ./.mysql:/var/lib/mysql

  web:
    env_file:
      - .env
    build:
      context: .
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
      - ~/.composer:/home/application/.composer
      - ~/.ssh:/home/application/.ssh
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - "db:database"
