services:
  db:
    image: mariadb:12.3.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: copona
    volumes:
      - ./.mysql:/var/lib/mysql

  web:
    build:
      context: .
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
      - ~/.composer:/home/application/.composer
      - ~/.ssh:/home/application/.ssh
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - "db:database"
    environment:
      DB_DRIVER: mysqli
      DB_HOSTNAME: database
      DB_DATABASE: copona
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_PREFIX: cp_
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      ADMIN_EMAIL: admin@example.com
